# Generated by Django 3.0.5 on 2021-03-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarticle',
            old_name='type',
            new_name='contenttype',
        ),
    ]
