# Generated by Django 3.1.7 on 2021-03-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarticle',
            old_name='user',
            new_name='author',
        ),
    ]
