# Generated by Django 3.1.7 on 2021-04-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_userprofile_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profileimg',
        ),
    ]
